<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="wangmengleideMacBook-Pro.local" name="com.course.chapter5.ExpectedException" tests="2" failures="0" timestamp="29 八月 2018 06:57:19 GMT" time="0.058" errors="0">
  <testcase name="runTimeExceptionFailed" time="0.056" classname="com.course.chapter5.ExpectedException"/>
  <testcase name="runTimeExceptionSuccess" time="0.002" classname="com.course.chapter5.ExpectedException"/>
</testsuite> <!-- com.course.chapter5.ExpectedException -->
